name: PR to Main Branch Warning

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        id: check_branch
        run: |
          echo "source_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT

      - name: Warn if PR is not from development
        if: steps.check_branch.outputs.source_branch != 'development'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":warning: Pull requests to `main` should only come from the `development` branch."
            });