name: Ruff Code Quality Check

on:
  pull_request:
    branches:
      - development

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check
        id: ruff
        run: |
          ruff check . > ruff_output.txt
          if [ $? -ne 0 ]; then
            echo "failed=true" >> $GITHUB_OUTPUT
          else
            echo "failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if Ruff fails
        if: steps.ruff.outputs.failed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('ruff_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: Ruff check failed!\n\n\`\`\`\n${output}\n\`\`\``
            });